<?php

/**
 * Created by PhpStorm.
 * User: Tiafeno
 * Date: 21/07/2017
 * Time: 23:16
 */
require_once 'Npm.php';

class Npm_en extends Npm
{
  public function __construct() {
    parent::__construct();
    $this->DefaultLang = array(
      'Currentlang' => 'eng',
      'Currentload' => 'english'
    );
    $this->getFactory();
  }

  public function index(){
    parent::index(); // TODO: Change the autogenerated stub
  }

  public function ours_actions_page() {
    parent::ours_actions_page();
  }

  public function products_page(){
    parent::produits_page();
  }

  public function contact_page(){
    parent::contact_page();
  }

  


}